version: '3.7'
services:
  postgres:
    container_name: postgres_db
    image: 'postgres:alpine'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=video_db
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5438:5432'
    volumes:
      - '../db-data:/var/lib/mysql/data'
      - './video.sql:/docker-entrypoint-initdb.d/video.sql'
  spring-app:
    container_name: spring-app
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 80:8080
volumes:
  postgres-data: null
 
